Making cdup not be greedy

diff --git a/cdup b/cdup
--- a/cdup
+++ b/cdup
@@ -3,14 +3,16 @@
 # Author: Weston Ruter (@westonruter) <http://weston.ruter.net/>
 # URL: https://github.com/westonruter/misc-cli-tools/blob/master/cdup
 # See also: https://github.com/westonruter/misc-cli-tools/blob/master/cddown
-# 
-# Bash shortcut function to cd you to ancestor directory named as first argument. 
+#
+# Bash shortcut function to cd you to ancestor directory named as first argument.
 # If DIRNAME is not supplied, then .. is used.
 # Stop having to cd ../../../..
 # Also supports substring matches for ancestor directory names.
-# Use `cd -` to undo, to restore old working directory. 
+# Use `cd -` to undo, to restore old working directory.
 # Use aliases for common directories, like: alias docroot="cdup docroot".
+# Provide a '...' alias to this for great justice.
 # Add function to your ~/.profile
+# @todo Add bash tab completion
 #
 # Example:
 # $ pwd
@@ -26,30 +28,30 @@
 # > /var/www/html/example.com
 
 function cdup {
-  
+
   # TODO: Allow an integer parameter to define the number of levels to jump up; allow it to be used with a named arg
-  
+
   if [ $# == 0 ]; then
     cd ..
     return 0
   fi
-  
+
   dir="$1"
   old=`pwd`
-  
+
   # Try matching the full segment in path name
-  new=`sed s:/\($dir\)/.*:/\1: <<< $old`
-  
+  new=`perl -pe "s{(.*/\Q$dir\E)(?=/|$).*?$}{\1};" <<< $old`
+
   # If failed, try partial match of segment
   if [ "$old" == "$new" ]; then
-    new=`sed "s:/\([^/]*$dir[^/]*\)/.*:/\1:" <<< $old`
+    new=`perl -pe "s{(.*/[^/]*?\Q$dir\E[^/]*?)(?=/|$).*?$}{\1}" <<< $old`
   fi
-  
+
   # No replacements done, so we failed
   if [ "$old" == "$new" ]; then
-    echo "Can't find '$dir' among ancestor directories." 1>&2
+    echo "Can't find '$dir' among ancestor directories ($old == $new)." 1>&2
     return 1
   fi
-  
+
   cd $new
 }
